// samples/vue-spring-boot/frontend/src/features/product-trading/master-detail/TradingDetailGrid.vue
<script setup lang="ts">
import type { Trading } from '../model/product-trading.types'

defineProps<{
  trades: Trading[]
}>()

const emit = defineEmits<{
  add: []
  edit: [trade: Trading]
  remove: [trade: Trading]
}>()

const numberFormatter = new Intl.NumberFormat('zh-TW', {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
})

function formatNumber(value: number): string {
  return numberFormatter.format(value)
}
</script>

<template>
  <section class="card app-card" data-testid="trading-detail-grid">
    <div class="card-header d-flex align-items-center justify-content-between gap-3">
      <div>
        <div class="section-title">Trading Detail</div>
        <div class="small text-secondary">
          SAMPLE_TRADING · {{ trades.length }} 筆
        </div>
      </div>

      <button class="btn btn-outline-primary btn-sm" type="button" @click="emit('add')">
        新增 Trading
      </button>
    </div>

    <div class="table-responsive">
      <table class="table table-hover align-middle mb-0">
        <thead>
          <tr>
            <th>Trade Date</th>
            <th>Type</th>
            <th>Counterparty</th>
            <th class="text-end">Quantity</th>
            <th class="text-end">Unit Price</th>
            <th class="text-end">Trade Amount</th>
            <th>Market</th>
            <th class="text-end">Action</th>
          </tr>
        </thead>
        <tbody>
          <tr v-if="trades.length === 0">
            <td colspan="8" class="text-center text-secondary py-4">
              目前沒有 Trading Detail。
            </td>
          </tr>

          <tr v-for="trade in trades" :key="trade.tradingId">
            <td>{{ trade.tradeDate }}</td>
            <td>
              <span
                class="badge"
                :class="trade.tradeType === 'BUY' ? 'text-bg-success' : 'text-bg-secondary'"
              >
                {{ trade.tradeType }}
              </span>
            </td>
            <td>
              <div>{{ trade.counterparty }}</div>
              <div v-if="trade.remark" class="small text-secondary text-truncate app-remark">
                {{ trade.remark }}
              </div>
            </td>
            <td class="text-end font-monospace">{{ formatNumber(trade.quantity) }}</td>
            <td class="text-end font-monospace">{{ formatNumber(trade.unitPrice) }}</td>
            <td class="text-end font-monospace fw-semibold">
              {{ formatNumber(trade.tradeAmount) }}
            </td>
            <td>{{ trade.marketCode || '—' }}</td>
            <td class="text-end text-nowrap">
              <button
                class="btn btn-link btn-sm text-decoration-none"
                type="button"
                @click="emit('edit', trade)"
              >
                編輯
              </button>
              <button
                class="btn btn-link btn-sm text-danger text-decoration-none"
                type="button"
                @click="emit('remove', trade)"
              >
                刪除
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
</template>

// samples/react-spring-boot/frontend/src/features/product-trading/master-detail/TradingDetailGrid.tsx
import type { Trading } from '../model/product-trading.types'

interface TradingDetailGridProps {
  trades: Trading[]
  onAdd: () => void
  onEdit: (trade: Trading) => void
  onRemove: (trade: Trading) => void
}

const numberFormatter = new Intl.NumberFormat('zh-TW', {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
})

export function TradingDetailGrid({
  trades,
  onAdd,
  onEdit,
  onRemove
}: TradingDetailGridProps) {
  return (
    <section className="card app-card" data-testid="trading-detail-grid">
      <div className="card-header d-flex align-items-center justify-content-between gap-3">
        <div>
          <div className="section-title">Trading Detail</div>
          <div className="small text-secondary">
            SAMPLE_TRADING · {trades.length} 筆
          </div>
        </div>

        <button
          className="btn btn-outline-primary btn-sm"
          type="button"
          onClick={onAdd}
        >
          新增 Trading
        </button>
      </div>

      <div className="table-responsive">
        <table className="table table-hover align-middle mb-0">
          <thead>
            <tr>
              <th>Trade Date</th>
              <th>Type</th>
              <th>Counterparty</th>
              <th className="text-end">Quantity</th>
              <th className="text-end">Unit Price</th>
              <th className="text-end">Trade Amount</th>
              <th>Market</th>
              <th className="text-end">Action</th>
            </tr>
          </thead>
          <tbody>
            {trades.length === 0 ? (
              <tr>
                <td colSpan={8} className="text-center text-secondary py-4">
                  目前沒有 Trading Detail。
                </td>
              </tr>
            ) : trades.map(trade => (
              <tr key={trade.tradingId}>
                <td>{trade.tradeDate}</td>
                <td>
                  <span
                    className={`badge ${
                      trade.tradeType === 'BUY'
                        ? 'text-bg-success'
                        : 'text-bg-secondary'
                    }`}
                  >
                    {trade.tradeType}
                  </span>
                </td>
                <td>
                  <div>{trade.counterparty}</div>
                  {trade.remark && (
                    <div className="small text-secondary text-truncate app-remark">
                      {trade.remark}
                    </div>
                  )}
                </td>
                <td className="text-end font-monospace">
                  {numberFormatter.format(trade.quantity)}
                </td>
                <td className="text-end font-monospace">
                  {numberFormatter.format(trade.unitPrice)}
                </td>
                <td className="text-end font-monospace fw-semibold">
                  {numberFormatter.format(trade.tradeAmount)}
                </td>
                <td>{trade.marketCode || '—'}</td>
                <td className="text-end text-nowrap">
                  <button
                    className="btn btn-link btn-sm text-decoration-none"
                    type="button"
                    onClick={() => onEdit(trade)}
                  >
                    編輯
                  </button>
                  <button
                    className="btn btn-link btn-sm text-danger text-decoration-none"
                    type="button"
                    onClick={() => onRemove(trade)}
                  >
                    刪除
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  )
}
